# Generated by Django 3.1.8 on 2021-06-03 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(default=None, max_length=100)),
                ('definition', models.CharField(default=None, max_length=400)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.collection')),
            ],
        ),
    ]
